use labsdb;

-- create table USER
CREATE TABLE IF NOT EXISTS usuarios(
    ID SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    usuario VARCHAR(20) NOT NULL DEFAULT '',
    clave VARCHAR(20) NOT NULL DEFAULT '',
    PRIMARY KEY (ID)
);

INSERT INTO usuarios (ID, USUARIO, CLAVE) VALUES (1, 'testuser', 'teXB5LK3JWG6g');

-- create procedure is valid USER

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_VALIDAR_USUARIO`
(IN PARAM_USER VARCHAR(255), IN PARAM_PASS VARCHAR(255))
BEGIN
    SET @S = CONCAT("SELECT COUNT(*) AS CANTIDAD FROM USUARIOS WHERE USUARIO = '", PARAM_USER ,"' AND CLAVE = '", PARAM_PASS, "';");

    PREPARE STMT FROM @S;
    EXECUTE STMT;
    DEALLOCATE PREPARE STMT;
END